kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 10.244.0.0/16 # set to Canal's default subnet
nodes:
- role: control-plane
- role: worker
- role: worker
