# Qserv operator CI workflow
---
name: "CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  main:
    name: Validate k8s install
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install k8s using kind
        run: |
          ./k8s-create.sh -s
      - name: Run tests
        run: |
          ./tests/launch.sh
